### ISSUE TITLE
ccmpred should use "-r" instead of -b

### ISSUE THREAD

**Issue by Ced3-han** [luoyunan/ECNet#4]
ccmpred doesn't have "-b" option, instead we should use "-r" for raw output

ccmpred example.psc example.mat -r example.braw -d 0

**Comment by jrhorne** [comment]
Yes, this should be updated in the docs. Thank you! 👍

**Comment by jrhorne** [comment]
Okay, this issue wasn't as simple as I first thought. Updating here for anyone else running into this issue.

- You do need CCMpred to output with the `-b` flag, as that is what `msgpack` needs for ECNet.
- The reason this causes issues is that you need to have `libmsgpack-dev` available when compiling CCMpred for that option to be available.

To fix this issue on Ubuntu:
1. `sudo apt update` then `sudo apt install libmsgpack-dev`
2. Then recompile and install CCMpred according to here [https://github.com/soedinglab/CCMpred](https://github.com/soedinglab/CCMpred)
3. You should have the `-b` flag available now when running `ccmpred -h`

Better docs in both packages might help alleviate these issues for getting local features

**Comment by luoyunan** [comment]
Thanks @Ced3-han and @jrhorne!

The `-b` flag is only available in the latest branch but not in the release of CCMPred. Actually this has been mentioned in the document (step 1 in the [feature generation section](https://github.com/luoyunan/ECNet/blob/main/README.md#generate-local-features-using-hhblits-and-ccmpred)).

I will update the doc to say this more explicitly. Thanks for the suggestion!

**Comment by jrhorne** [comment]
Thanks! I know this is on CCMpred, but it took some digging [here](https://github.com/soedinglab/CCMpred/blob/2919b9c9ae976f73bc4dbb67908170afc3578da8/src/ccmpred.c#L202-L203) to realize I needed msgpack available first.

**Comment by luoyunan** [comment]
Doc was revised in https://github.com/luoyunan/ECNet/commit/436eb6cec6d28697a04ce9d30433961731659139
